### ISSUE TITLE
Old cluster name is used in kubeconfig after rename

### ISSUE THREAD

**Issue by Shark** [civo/cli-rubygem#54]
When running the command:

```
$ civo kubernetes rename playground --name=civoplay
```

The old name still shows up:

```yml
$ civo kubernetes config civoplay
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DELETED
    server: https://DELETED
  name: playground
contexts:
- context:
    cluster: playground
    user: playground
  name: playground
current-context: playground
kind: Config
preferences: {}
users:
- name: playground
  user:
    password: DELETED
    username: admin
```

While `civo kubernetes list` shows the new name:

```
$ civo kubernetes list
+--------------------------------------+----------+---------+----------+---------+------------+
| ID                                   | Name     | # Nodes | Size     | Version | Status     |
+--------------------------------------+----------+---------+----------+---------+------------+
| DELETED | civoplay | 3       | g2.small | 1.0.0   | INSTALLING |
+--------------------------------------+----------+---------+----------+---------+------------+
```

Using the most recent Docker CLI image (`6fc7d41d6aa4`), though not the most recent version:

```
$ civo version
You are running v0.5.6 of Civo CLI, but are out of date because v0.5.7 is available
``
